
name: Converter DARF (PDF -> Excel)

on:
  workflow_dispatch:
  push:
    paths:
      - "pdfs/**/*.pdf"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependências
        run: npm ci || npm i

      - name: Criar pasta de saída
        run: mkdir -p dist

      - name: Converter PDFs para Excel
        run: npm run build

      - name: Publicar artifact (Excel)
        uses: actions/upload-artifact@v4
        with:
          name: saida-excel
          path: dist/saida.xlsx
          if-no-files-found: error

      # ---- Exemplo (opcional) para comitar a saída ----
      # Para ativar, remova o comentário deste bloco e adicione permissions: contents: write no job
      # - name: Commit & push do Excel
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     add: "dist/saida.xlsx"
      #     message: "chore: atualiza planilha gerada automaticamente"
      #     default_author: github_actions
